// examples/react-app/TodoApp.jsx
import React, { useState } from 'react';
import { useStore } from '../../adapters/react';

/**
 * React Todo App Component
 * Demonstrates how to use the framework-agnostic business logic with React
 */
export function TodoApp({ store, todoService }) {
  const state = useStore(store);
  const [inputValue, setInputValue] = useState('');
  const [filter, setFilter] = useState('all'); // all, active, completed

  const handleAddTodo = (e) => {
    e.preventDefault();
    if (inputValue.trim()) {
      try {
        todoService.addTodo(inputValue);
        setInputValue('');
      } catch (error) {
        alert(error.message);
      }
    }
  };

  const getFilteredTodos = () => {
    switch (filter) {
      case 'active':
        return todoService.getActiveTodos();
      case 'completed':
        return todoService.getCompletedTodos();
      default:
        return todoService.getAllTodos();
    }
  };

  const stats = todoService.getStats();

  return (
    <div style={styles.container}>
      <h1 style={styles.title}>Todo App - React</h1>
      
      <form onSubmit={handleAddTodo} style={styles.form}>
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="What needs to be done?"
          style={styles.input}
        />
        <button type="submit" style={styles.addButton}>
          Add
        </button>
      </form>

      <div style={styles.filters}>
        <button
          onClick={() => setFilter('all')}
          style={{
            ...styles.filterButton,
            ...(filter === 'all' ? styles.filterButtonActive : {})
          }}
        >
          All ({stats.total})
        </button>
        <button
          onClick={() => setFilter('active')}
          style={{
            ...styles.filterButton,
            ...(filter === 'active' ? styles.filterButtonActive : {})
          }}
        >
          Active ({stats.active})
        </button>
        <button
          onClick={() => setFilter('completed')}
          style={{
            ...styles.filterButton,
            ...(filter === 'completed' ? styles.filterButtonActive : {})
          }}
        >
          Completed ({stats.completed})
        </button>
      </div>

      <ul style={styles.todoList}>
        {getFilteredTodos().map((todo) => (
          <li key={todo.id} style={styles.todoItem}>
            <input
              type="checkbox"
              checked={todo.completed}
              onChange={() => todoService.toggleTodo(todo.id)}
              style={styles.checkbox}
            />
            <span
              style={{
                ...styles.todoText,
                ...(todo.completed ? styles.todoTextCompleted : {})
              }}
            >
              {todo.title}
            </span>
            <button
              onClick={() => todoService.deleteTodo(todo.id)}
              style={styles.deleteButton}
            >
              Delete
            </button>
          </li>
        ))}
      </ul>

      {stats.completed > 0 && (
        <button
          onClick={() => todoService.clearCompleted()}
          style={styles.clearButton}
        >
          Clear Completed
        </button>
      )}

      <div style={styles.info}>
        <p>Framework: <strong>React</strong></p>
        <p>Business Logic: <strong>Framework-Agnostic</strong></p>
      </div>
    </div>
  );
}

const styles = {
  container: {
    maxWidth: '600px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: 'Arial, sans-serif'
  },
  title: {
    textAlign: 'center',
    color: '#333'
  },
  form: {
    display: 'flex',
    marginBottom: '20px'
  },
  input: {
    flex: 1,
    padding: '10px',
    fontSize: '16px',
    border: '1px solid #ddd',
    borderRadius: '4px 0 0 4px'
  },
  addButton: {
    padding: '10px 20px',
    fontSize: '16px',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '0 4px 4px 0',
    cursor: 'pointer'
  },
  filters: {
    display: 'flex',
    gap: '10px',
    marginBottom: '20px'
  },
  filterButton: {
    flex: 1,
    padding: '8px',
    backgroundColor: '#f0f0f0',
    border: '1px solid #ddd',
    borderRadius: '4px',
    cursor: 'pointer'
  },
  filterButtonActive: {
    backgroundColor: '#2196F3',
    color: 'white',
    borderColor: '#2196F3'
  },
  todoList: {
    listStyle: 'none',
    padding: 0
  },
  todoItem: {
    display: 'flex',
    alignItems: 'center',
    padding: '10px',
    backgroundColor: '#f9f9f9',
    marginBottom: '8px',
    borderRadius: '4px'
  },
  checkbox: {
    marginRight: '10px',
    width: '20px',
    height: '20px',
    cursor: 'pointer'
  },
  todoText: {
    flex: 1,
    fontSize: '16px'
  },
  todoTextCompleted: {
    textDecoration: 'line-through',
    color: '#999'
  },
  deleteButton: {
    padding: '5px 10px',
    backgroundColor: '#f44336',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer'
  },
  clearButton: {
    width: '100%',
    padding: '10px',
    backgroundColor: '#ff9800',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    marginTop: '20px'
  },
  info: {
    marginTop: '30px',
    padding: '15px',
    backgroundColor: '#e3f2fd',
    borderRadius: '4px',
    textAlign: 'center'
  }
};

// examples/vue-app/TodoApp.vue
<template>
  <div class="container">
    <h1 class="title">Todo App - Vue</h1>
    
    <form @submit.prevent="handleAddTodo" class="form">
      <input
        v-model="inputValue"
        type="text"
        placeholder="What needs to be done?"
        class="input"
      />
      <button type="submit" class="add-button">
        Add
      </button>
    </form>

    <div class="filters">
      <button
        @click="filter = 'all'"
        :class="['filter-button', { active: filter === 'all' }]"
      >
        All ({{ stats.total }})
      </button>
      <button
        @click="filter = 'active'"
        :class="['filter-button', { active: filter === 'active' }]"
      >
        Active ({{ stats.active }})
      </button>
      <button
        @click="filter = 'completed'"
        :class="['filter-button', { active: filter === 'completed' }]"
      >
        Completed ({{ stats.completed }})
      </button>
    </div>

    <ul class="todo-list">
      <li v-for="todo in filteredTodos" :key="todo.id" class="todo-item">
        <input
          type="checkbox"
          :checked="todo.completed"
          @change="todoService.toggleTodo(todo.id)"
          class="checkbox"
        />
        <span
          :class="['todo-text', { completed: todo.completed }]"
        >
          {{ todo.title }}
        </span>
        <button
          @click="todoService.deleteTodo(todo.id)"
          class="delete-button"
        >
          Delete
        </button>
      </li>
    </ul>

    <button
      v-if="stats.completed > 0"
      @click="todoService.clearCompleted()"
      class="clear-button"
    >
      Clear Completed
    </button>

    <div class="info">
      <p>Framework: <strong>Vue</strong></p>
      <p>Business Logic: <strong>Framework-Agnostic</strong></p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useStore } from '../../src/adapters/vue';

const props = defineProps({
  store: Object,
  todoService: Object
});

const state = useStore(props.store);
const inputValue = ref('');
const filter = ref('all');

const handleAddTodo = () => {
  if (inputValue.value.trim()) {
    try {
      props.todoService.addTodo(inputValue.value);
      inputValue.value = '';
    } catch (error) {
      alert(error.message);
    }
  }
};

const filteredTodos = computed(() => {
  switch (filter.value) {
    case 'active':
      return props.todoService.getActiveTodos();
    case 'completed':
      return props.todoService.getCompletedTodos();
    default:
      return props.todoService.getAllTodos();
  }
});

const stats = computed(() => props.todoService.getStats());
</script>

<style scoped>
.container {
  max-width: 600px;
  margin: 0 auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

.title {
  text-align: center;
  color: #333;
}

.form {
  display: flex;
  margin-bottom: 20px;
}

.input {
  flex: 1;
  padding: 10px;
  font-size: 16px;
  border: 1px solid #ddd;
  border-radius: 4px 0 0 4px;
}

.add-button {
  padding: 10px 20px;
  font-size: 16px;
  background-color: #4CAF50;
  color: white;
  border: none;
  border-radius: 0 4px 4px 0;
  cursor: pointer;
}

.filters {
  display: flex;
  gap: 10px;
  margin-bottom: 20px;
}

.filter-button {
  flex: 1;
  padding: 8px;
  background-color: #f0f0f0;
  border: 1px solid #ddd;
  border-radius: 4px;
  cursor: pointer;
}

.filter-button.active {
  background-color: #2196F3;
  color: white;
  border-color: #2196F3;
}

.todo-list {
  list-style: none;
  padding: 0;
}

.todo-item {
  display: flex;
  align-items: center;
  padding: 10px;
  background-color: #f9f9f9;
  margin-bottom: 8px;
  border-radius: 4px;
}

.checkbox {
  margin-right: 10px;
  width: 20px;
  height: 20px;
  cursor: pointer;
}

.todo-text {
  flex: 1;
  font-size: 16px;
}

.todo-text.completed {
  text-decoration: line-through;
  color: #999;
}

.delete-button {
  padding: 5px 10px;
  background-color: #f44336;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.clear-button {
  width: 100%;
  padding: 10px;
  background-color: #ff9800;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  margin-top: 20px;
}

.info {
  margin-top: 30px;
  padding: 15px;
  background-color: #e3f2fd;
  border-radius: 4px;
  text-align: center;
}
</style>
